apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: nodejs-test-rw-gh 
  janus-idp.io/tekton: nodejs-test-rw-gh
  backstage.io/kubernetes-id: nodejs-test-rw-gh
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: nodejs-test-rw-gh
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  